### ISSUE TITLE
Matlab examples

### ISSUE THREAD

**Issue by neurolabusc** [openneuropet/PET2BIDS#85]
1. The [Matlab Readme.md](https://github.com/openneuropet/PET2BIDS/blob/28aae3fab22309047d36d867c624cd629c921ca6/matlab/Readme.md) suggests provides an example for specifying the meta data:

```
metadata = get_pet_metadata('Scanner','SiemensHRRT','TimeZero','XXX','tracer','DASB','Radionuclide','C11', ...
                        'Radioactivity', 605.3220,'InjectedMass', 1.5934,'MolarActivity', 107.66)
```
Running this command in Matlab generates an error:
```
Error using get_pet_metadata (line 118)
there are not enough radioactivity related inputs to make sense of the data - see help
```

2. Both 'niftiwrite' and 'niftiread' require Image Processing Toolbox. Is it possible to remove this dependency? I often use [nii_tool](https://github.com/xiangruili/dicm2nii), though you could also look at Jimmy Shens tools.

**Comment by CPernet** [comment]
nitfi write  - would be a good enhancement although I did not find a good way to use this from ecat because it assumes tings from dicom, i was looking at alternatives that would work for octave -- we actually donæt need a whole dcm things just a nifti write  -- now in https://github.com/openneuropet/PET2BIDS/issues/88 

in all fairness for now the doc says it's a dependency -- leaving it to @bendhouseart to fix this
